### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by pmandroid** [VarunS2002/Python-NSE-Option-Chain-Analyzer#25]
[2021-10-04 14:46:28 - INFO ] Windows 10 .py version 5.3 
[2021-10-04 14:46:36 - ERROR] Exception in Tkinter callback
[2021-10-04 14:46:36 - ERROR] Traceback (most recent call last):
  File "C:\Users\prash\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 1892, in __call__
[2021-10-04 14:46:36 - ERROR]     return self.func(*args)
  File "C:\Users\prash\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 814, in callit
[2021-10-04 14:46:36 - ERROR]     func(*args)
  File "D:/python-workspace/Python-NSE-Option-Chain-Analyzer/NSE_Option_Chain_Analyzer.py", line 1571, in main
[2021-10-04 14:46:36 - ERROR]     self.set_values()
  File "D:/python-workspace/Python-NSE-Option-Chain-Analyzer/NSE_Option_Chain_Analyzer.py", line 1397, in set_values
[2021-10-04 14:46:36 - ERROR]     self.sheet.see(last_row)
  File "D:\python-workspace\Python-NSE-Option-Chain-Analyzer\venv\lib\site-packages\tksheet\_tksheet.py", line 1169, in see
[2021-10-04 14:46:36 - ERROR]     self.MT.see(row, column, keep_yscroll, keep_xscroll, bottom_right_corner, check_cell_visibility = check_cell_visibility, redraw = redraw)
  File "D:\python-workspace\Python-NSE-Option-Chain-Analyzer\venv\lib\site-packages\tksheet\_tksheet_main_table.py", line 1164, in see
[2021-10-04 14:46:36 - ERROR]     yvis, xvis = self.cell_is_completely_visible(r = r, c = c, separate_axes = True)
  File "D:\python-workspace\Python-NSE-Option-Chain-Analyzer\venv\lib\site-packages\tksheet\_tksheet_main_table.py", line 1220, in cell_is_completely_visible
[2021-10-04 14:46:36 - ERROR]     x1, y1, x2, y2 = self.GetCellCoords(r = r, c = c, sel = True)
  File "D:\python-workspace\Python-NSE-Option-Chain-Analyzer\venv\lib\site-packages\tksheet\_tksheet_main_table.py", line 2610, in GetCellCoords
[2021-10-04 14:46:36 - ERROR]     return self.col_positions[c] + 1,self.row_positions[r] + 1, self.col_positions[c + 1], self.row_positions[r + 1]
**IndexError: list index out of range**

![Screenshot (29)](https://user-images.githubusercontent.com/32534345/135826755-031d22e5-eb03-4863-8180-20ea721f6b35.png)

**Comment by VarunS2002** [comment]
#24
Same error happens on MacOS so it's a platform independent issue. 
Will look into this.

**Comment by VarunS2002** [comment]
@pmandroid
Possibly fixed the issue in fd0981cf846c08628bb69d1f450a76ecb6df570e
Downgrade (or upgrade) to version 5.0.24 of tksheet using `pip install tksheet==5.0.24` and get back

**Comment by dipankar-npowered** [comment]
> @pmandroid Possibly fixed the issue in [fd0981c](https://github.com/VarunS2002/Python-NSE-Option-Chain-Analyzer/commit/fd0981cf846c08628bb69d1f450a76ecb6df570e) Downgrade (or upgrade) to version 5.0.24 of tksheet using `pip install tksheet==5.0.24` and get back

It's working
