### ISSUE TITLE
Quitting program raises exceptions:

### ISSUE THREAD

**Issue by richdevboston** [VarunS2002/Python-NSE-Option-Chain-Analyzer#28]
Quitting program raises exceptions shown below:

streamtologger appears to not be working also.  No log file is produced.

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\consuming_http\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "C:\ProgramData\Anaconda3\envs\consuming_http\lib\tkinter\__init__.py", line 814, in callit
    func(*args)
  File "C:\Users\richadmin\AppData\Local\Temp/ipykernel_23096/1352159003.py", line 1552, in main
    self.set_values()
  File "C:\Users\richadmin\AppData\Local\Temp/ipykernel_23096/1352159003.py", line 1378, in set_values
    self.sheet.see(last_row)
  File "C:\ProgramData\Anaconda3\envs\consuming_http\lib\site-packages\tksheet\_tksheet.py", line 1128, in see
    self.MT.see(row, column, keep_yscroll, keep_xscroll, bottom_right_corner, check_cell_visibility = check_cell_visibility, redraw = redraw)
  File "C:\ProgramData\Anaconda3\envs\consuming_http\lib\site-packages\tksheet\_tksheet_main_table.py", line 1050, in see
    yvis, xvis = self.cell_is_completely_visible(r = r, c = c, separate_axes = True)
  File "C:\ProgramData\Anaconda3\envs\consuming_http\lib\site-packages\tksheet\_tksheet_main_table.py", line 1106, in cell_is_completely_visible
    x1, y1, x2, y2 = self.GetCellCoords(r = r, c = c, sel = True)
  File "C:\ProgramData\Anaconda3\envs\consuming_http\lib\site-packages\tksheet\_tksheet_main_table.py", line 2506, in GetCellCoords
    return self.col_positions[c] + 1,self.row_positions[r] + 1, self.col_positions[c + 1], self.row_positions[r + 1]
IndexError: list index out of range
```

**Comment by VarunS2002** [comment]
Probably same as #25 and #24
Downgrade (or upgrade) to version 5.0.24 of tksheet using `pip install tksheet==5.0.24` and get back

**Comment by VarunS2002** [comment]
@richdevboston This issue will be closed in 3 days due to inactivity
