### ISSUE TITLE
Exception in tkinter module

### ISSUE THREAD

**Issue by jainankur11788** [VarunS2002/Python-NSE-Option-Chain-Analyzer#36]
$ python3 oi.py 
Exception in Tkinter callback
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/tkinter/__init__.py", line 1883, in __call__
    return self.func(*args)
  File "oi.py", line 566, in start
    self.main_win()
  File "oi.py", line 960, in main_win
    self.sheet.enable_bindings(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tksheet/_tksheet.py", line 643, in enable_bindings
    self.MT.enable_bindings(bindings)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tksheet/_tksheet_main_table.py", line 2067, in enable_bindings
    self.enable_bindings_internal(binding.lower())
AttributeError: 'tuple' object has no attribute 'lower'

**Comment by VarunS2002** [comment]
@jainankur11788 
Which version of tksheet are you using?

**Comment by VarunS2002** [comment]
Type `pip freeze` or `pip3 freeze` in your terminal to check

**Comment by VarunS2002** [comment]
@jainankur11788 
As it turns out, this is an issue with the `tksheet` library itself -> https://github.com/ragardner/tksheet/issues/117
This should be fixed soon but for the time being you can switch to version `5.3.5`
Run `pip install tksheet==5.3.5` or `pip3 install tksheet==5.3.5` in your terminal

**Comment by jainankur11788** [comment]
Cool
Downgrading the version of tksheet to 5.3.5 works.
